load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

# CLEAN - all deps are actually used.
swift_library(
    name = "CleanTarget",
    srcs = ["CleanTarget.swift"],
    module_name = "CleanTarget",
    deps = [
        "//example/Deps/TransitiveDep",
        "//example/Deps/DirectDepWithTransitive",
        "//example/Deps/LibB",
    ],
    visibility = ["//example:__subpackages__"],
)
